### ISSUE TITLE
dagger.android 让主工程和模块的一些类耦合在一起了，有什么好解决办法么？

### ISSUE THREAD

**Issue by lorcanluo** [YummyLau/RapidDvpt#1]
你好，能描述下场景或者代码贴下吗？
目前项目的di部分正在优化哈，一起交流

**Comment by YummyLau** [comment]
你好，能描述下场景或者代码贴下吗？
目前项目的di部分正在优化哈，一起交流

**Comment by lorcanluo** [comment]
```
@Singleton
@Component(modules = {
        AndroidInjectionModule.class,
        AndroidSupportInjectionModule.class,
        AppModule.class,
        MainActivityModule.class,
        TestActivityModule.class
})
public interface AppComponent {
    @Component.Builder
    interface Builder {
        @BindsInstance
        Builder application(Application application);

        AppComponent build();
    }

    void inject(DemoApplication demoApplication);
}
```
dagger.android 中 AppComponent 里面需要在Component里面添加Activity里面的ActivityModule，这点感觉耦合。

**Comment by YummyLau** [comment]
嗯嗯，最新更新版本解决了这个问题。
我的理解是DI的最大作用是解决自己无法控制生成的类的生命周期，比如activity，fragment，viewmodel。
针对这些的处理
在componentlib中添加viewmodule工厂di :ViewModelFactoryModule.java
每一个独立的组件封装一个最终include该组件的所有依赖，比如featureConponent中对应FeatureModule。
最后在外层壳app直接include这个module即可。不会存在任何activity的耦合。
后续会添加组件的动态解绑和注入。
更新下最新代码，看下是否能解决你的 问题。

**Comment by lorcanluo** [comment]
谢谢 我最近也在折腾一个组件化的新框架

**Comment by YummyLau** [comment]
嗯，多交流一起学习。
